### PR TITLE
Updated to ALPHA 3.0.0

### PR DESCRIPTION
**Pull request by artulloss**
Everything should work as it did before, however this plugin disappointingly does nothing

Edit: I did however add type hints to a lot more things

### CODE REVIEW

**Comment by OGFris** [comment]
This plugin works more as an example or maybe we should call it a barebone project for beginners to learn from it because I honnestely lost motivation for it but thanks for the update!

**Comment by artulloss** [comment]
Yeah, no problem. I updated the one by Ad as well, but it's utter shit compared to this, even if this doesn't work.

**Comment by OGFris** [comment]
Please keep it cool man his work is good as well!

**Comment by artulloss** [comment]
Yeah, it's just that after cleaning up all the grammatical mistakes, then fixing up the organization of the code and updating outdated API stuff, I was left disappointed that it doesn't even check if there is only 1 person, it uses resistance to keep players from taking damage when it starts. Overall the plugin felt poorly done, so I decided not to pr the fixes to save people the trouble of dealing with it. It made me wonder how the plugin ever had 19 stars...

**Comment by ZeldrisNetwork** [comment]
the /uhc command does not work

**Pull request merged**
